#define             VOID            1
#define             VAR             2
#define             CONST           3
#define             INT             4
#define             ID              5
#define             INTLITERAL      6
#define             STRINGLITERAL   7
#define             IF              8
#define             ELSE            9
#define             WHILE           10
#define             PRINT           11
#define             LPAREN          12
#define             RPAREN          13
#define             LLLAVE          14
#define             RLLAVE          15
#define             SEMICOLON       16
#define             COMMA           17
#define             ASSIGN          18
#define             PLUSOP          19
#define             MINUSOP         20
#define             MULTIOP         21
#define             BARRAD          22
#define             READ            23